{{- $metrics := toYaml .Values.metrics -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-map-{{ template "promitor-agent-resource-discovery.fullname" . }}
  labels:
    app: {{ template "promitor-agent-resource-discovery.name" . }}
    chart: {{ template "promitor-agent-resource-discovery.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  runtime.yaml: |-
      server:
        httpPort: {{ .Values.service.targetPort | quote }}
  metrics-declaration.yaml: |-
    version: v1
    azureMetadata:
      tenantId: {{ .Values.azureMetadata.tenantId }}
      subscriptionId: {{ .Values.azureMetadata.subscriptionId }}
      resourceGroupName: {{ .Values.azureMetadata.resourceGroupName }}
    metrics:
{{ tpl $metrics . | indent 4 }}
